name: Development workflow

on:
  pull_request:
    branches:
      - **

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Check out code
      #   uses: actions/checkout@v2

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
